// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package verkle

import (
	"encoding/json"
)

var _ = (*keyValuePairMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (k KeyValuePair) MarshalJSON() ([]byte, error) {
	type KeyValuePair struct {
		Key   []byte `json:"key"`
		Value []byte `json:"-"`
		Val   string `json:"value"`
	}
	var enc KeyValuePair
	enc.Key = k.Key
	enc.Value = k.Value
	enc.Val = k.Val()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (k *KeyValuePair) UnmarshalJSON(input []byte) error {
	type KeyValuePair struct {
		Key   []byte `json:"key"`
		Value []byte `json:"-"`
	}
	var dec KeyValuePair
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Key != nil {
		k.Key = dec.Key
	}
	if dec.Value != nil {
		k.Value = dec.Value
	}
	return nil
}
