// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package verkle

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *IPAProof) SizeSSZ() uint32 {
	return 8*32 + 8*32 + 32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *IPAProof) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUnsafeArrayOfStaticBytes(codec, obj.CL[:]) // Field  (0) -              CL - 256 bytes
	ssz.DefineUnsafeArrayOfStaticBytes(codec, obj.CR[:]) // Field  (1) -              CR - 256 bytes
	ssz.DefineStaticBytes(codec, &obj.FinalEvaluation)   // Field  (2) - FinalEvaluation -  32 bytes
}
