name: Block replay test

on:
  push:
    branches: [ master ]

jobs:
  replay:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Extract converted db
      run: |
        mkdir .ethereum
        tar xf /home/devops/verkle-test-dependencies/replay_converted.tgz --strip-components=1 -C .ethereum

    - name: Download geth from the proper repo
      run: git clone https://github.com/gballet/go-ethereum -b overlay/changes-for-replay geth
      # run: git clone https://github.com/gballet/go-ethereum -b beverly-hills+sepolia-replay geth

    - name: Edit geth to use this repo and build it
      run: |
        cd geth
        cp /home/devops/verkle-test-dependencies/fork.txt .
        go mod edit -replace=github.com/ethereum/go-verkle=$PWD/..
        go mod edit -replace=github.com/crate-crypto/go-ipa=github.com/crate-crypto/go-ipa@`grep go-ipa ../go.mod | cut -d'-' -f 5`
        go mod download github.com/crate-crypto/go-ipa
        go mod tidy
        go build ./cmd/geth/...
 
    - name: Run replay
      run: |
        cd geth
        echo 230080 > conversion.txt
        ./geth import --datadir=../.ethereum /home/devops/verkle-test-dependencies/next_blocks4

    # - name: Upload profiler file
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: cpu.out
    #     path: ./geth/cpu.out

    # - name: Generate profile diagram
    #   run: |
    #     cd geth
    #     go tool pprof -png cpu.out > profile001.png

    # - name: Upload profiler picture
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: profile.png
    #     path: ./geth/profile001.png

    - name: Cleanup
      if: always()
      run: rm -rf geth .ethereum